import os
import csv

def load_lookup_dictionary(dict_path):
    """
    Loads the dictionary CSV file from Step 3 into a Python dictionary
    for fast lookups. The key will be the 'Fused_Index' and the value
    will be the unique 'Arm_Length_ID'.
    """
    lookup_dict = {}
    try:
        with open(dict_path, 'r', newline='') as f:
            reader = csv.reader(f)
            next(reader)  # Skip the header row
            # The dictionary maps column 0 (e.g., 'Arm01_109') to column 1 (e.g., 'Arm01_95')
            for row in reader:
                if len(row) >= 2:
                    fused_index = row[0]
                    arm_length_id = row[1]
                    lookup_dict[fused_index] = arm_length_id
    except FileNotFoundError:
        print(f"Error: Dictionary file not found at '{dict_path}'")
        print("Please ensure the script from Step 3 has been run successfully and the output file is in the correct location.")
        exit() # Exit the script if the crucial lookup file is missing
    return lookup_dict

# --- File Paths ---
# This is the main input file for this step
genotype_input_file = "../GenotypicTable_nSSR_FullLength_ParameterSet1_sa50_sb10_m15_n20.txt"

# This is the dictionary file generated by the previous step (Step3)
dictionary_file = '../new_output/AlleleInfo_dictionary.csv'

# This will be the final output file for this script
output_file = "../new_output/GenotypicTable_fused.txt"

# --- Main Script Logic ---

# 1. Load the lookup dictionary from the Step 3 output file
allele_lookup = load_lookup_dictionary(dictionary_file)

# 2. Process the main genotypic table
print("Processing genotypic table...")
with open(genotype_input_file, "r") as fin, open(output_file, "w", newline='') as fout:
    lines = fin.readlines()
    headers = lines[0].strip().split("\t")

    writer = csv.writer(fout, delimiter='\t')
    writer.writerow(headers)

    for line in lines[1:]:
        cells = line.strip().split("\t")
        # Pad the row with 'NA' if it's shorter than the header
        if len(cells) < len(headers):
            cells += ["NA"] * (len(headers) - len(cells))

        new_cells = [cells[0]]  # Keep the first column (the sample name)

        # Iterate through the remaining columns
        for i in range(1, len(headers)):
            # Determine the correct header for the allele (e.g., 'Arm01')
            pair_header_idx = i if i % 2 == 1 else i - 1
            pair_header = headers[pair_header_idx]
            value = cells[i]

            if value not in ["NA", ""]:
                # Create the fused key to search for in the dictionary (e.g., 'Arm01_109')
                lookup_key = f"{pair_header}_{value}"

                # Look up the key. If found, use the corresponding unique ID.
                # If not found, use 'NA' as a placeholder.
                final_allele_id = allele_lookup.get(lookup_key, "NA")
                new_cells.append(final_allele_id)
            else:
                new_cells.append("NA")

        writer.writerow(new_cells)

print(f"Transformation complete. Final table written to {output_file}")
